---
- name: Include updatePassword.yml
  include: updatePassword.yml
  when:
    accounts['updatePassword']['username'] is defined
    and
    accounts['updatePassword']['username'] | length > 0

- name: Include remove.yml
  include: remove.yml
  when:
    accounts['remove']['user'] is defined
    and
    accounts['remove']['user'] | length > 0
