---
- name: Change {{ accounts.updatePassword.username }} password
  block:
    - lineinfile:
        path: /tmp/pwd.txt
        line: "{{ accounts.updatePassword.password }}"
        create: yes
        state: present
        mode: 0400

    - shell: echo "{{ accounts.updatePassword.username }}":$(cat /tmp/pwd.txt) | chpasswd
      args:
        executable: /bin/bash

    - file:
        path: /tmp/pwd.txt
        state: absent
