---
- name: Decrypt password
  debug:
    msg: "{{ accounts.updatePassword.password }}"
  register: passwordUnencrypted

- name: Change {{ accounts.updatePassword.username }} password
  user:
    name: "{{ accounts.updatePassword.username }}"
    update_password: always
    password: "{{ passwordUnencrypted.msg|password_hash('sha512') }}"
